name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - run: uv sync --all-extras --dev
      - run: uv run ruff check
      - run: uv run ruff format --diff
      - run: uv run ty check
      # - run: uv run pytest
      # - run: uv run mypy .
